services:
  - type: web
    name: learnhub-backend
    env: docker
    plan: free
    docker:
      dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
    domains:
      - learnhub-backend.onrender.com